// Photo gallery — data comes from js/gallery-data.js (generated by scripts/build-gallery.py)
(() => {
  const years = window.GALLERY || [];
  const yearsEl = document.getElementById('galleryYears');
  const groupsEl = document.getElementById('galleryGroups');
  const countEl = document.getElementById('galleryCount');
  const grid = document.getElementById('galleryGrid');
  const sentinel = document.getElementById('gallerySentinel');
  if (!grid || !years.length) return;

  const BATCH = 48;
  let year = null;      // current year entry
  let group = -1;       // selected group index, -1 = all
  let photos = [];      // photos currently shown (after filter)
  let rendered = 0;

  const photoUrl = (dir, file) => `img/gallery/${encodeURIComponent(dir)}/${encodeURIComponent(file)}`;
  const thumbUrl = (dir, file) => `img/gallery-thumbs/${encodeURIComponent(dir)}/${encodeURIComponent(file.replace(/\.[^.]+$/, '.webp'))}`;

  const button = (label, className, onClick) => {
    const b = document.createElement('button');
    b.type = 'button';
    b.className = className;
    b.textContent = label;
    b.addEventListener('click', onClick);
    return b;
  };

  // Year tabs
  years.forEach(y => {
    const b = button(y.year, 'gallery__year', () => selectYear(y.year));
    b.setAttribute('role', 'tab');
    b.dataset.year = y.year;
    yearsEl.appendChild(b);
  });

  function selectYear(yearLabel, pushHash = true) {
    year = years.find(y => y.year === yearLabel) || years[0];
    group = -1;
    yearsEl.querySelectorAll('.gallery__year').forEach(b => {
      b.setAttribute('aria-selected', b.dataset.year === year.year);
    });
    if (pushHash) history.replaceState(null, '', '#' + year.year);
    renderGroups();
    applyFilter();
  }

  // Group (artist) filter chips — only when the year's file names define groups
  function renderGroups() {
    groupsEl.innerHTML = '';
    groupsEl.hidden = year.groups.length < 2;
    if (groupsEl.hidden) return;
    const chips = [['Alles', -1], ...year.groups.map((g, i) => [g, i])];
    chips.forEach(([label, index]) => {
      const b = button(label, 'gallery__group', () => {
        group = index;
        groupsEl.querySelectorAll('.gallery__group').forEach(c => c.setAttribute('aria-pressed', c === b));
        applyFilter();
      });
      b.setAttribute('aria-pressed', index === group);
      groupsEl.appendChild(b);
    });
  }

  function applyFilter() {
    photos = year.photos.filter(([, g]) => group === -1 || g === group);
    countEl.textContent = `${photos.length} foto's`;
    grid.innerHTML = '';
    rendered = 0;
    renderMore();
  }

  function renderMore() {
    const end = Math.min(rendered + BATCH, photos.length);
    const frag = document.createDocumentFragment();
    for (let i = rendered; i < end; i++) {
      const [file, g] = photos[i];
      const a = document.createElement('a');
      a.className = 'gallery__item';
      a.href = photoUrl(year.dir, file);
      a.dataset.index = i;
      const img = document.createElement('img');
      img.src = thumbUrl(year.dir, file);
      img.alt = `Nerorock ${year.year}` + (g >= 0 ? ` — ${year.groups[g]}` : '');
      img.loading = 'lazy';
      img.decoding = 'async';
      a.appendChild(img);
      frag.appendChild(a);
    }
    grid.appendChild(frag);
    rendered = end;
  }

  // Load more thumbnails as the user scrolls near the end
  new IntersectionObserver(entries => {
    if (entries[0].isIntersecting && rendered < photos.length) renderMore();
  }, { rootMargin: '800px 0px' }).observe(sentinel);

  // Lightbox
  const lightbox = document.getElementById('lightbox');
  const lbImg = document.getElementById('lightboxImg');
  const lbCaption = document.getElementById('lightboxCaption');
  let current = 0;
  let lastFocus = null;

  function show(index) {
    current = (index + photos.length) % photos.length;
    const [file, g] = photos[current];
    lbImg.src = photoUrl(year.dir, file);
    lbImg.alt = `Nerorock ${year.year}` + (g >= 0 ? ` — ${year.groups[g]}` : '');
    lbCaption.textContent = `${g >= 0 ? year.groups[g] + ' · ' : ''}${current + 1} / ${photos.length}`;
    // Preload neighbours for snappy navigation
    [current + 1, current - 1].forEach(i => {
      const p = photos[(i + photos.length) % photos.length];
      new Image().src = photoUrl(year.dir, p[0]);
    });
  }

  function open(index) {
    lastFocus = document.activeElement;
    lightbox.hidden = false;
    document.body.style.overflow = 'hidden';
    show(index);
    document.getElementById('lightboxClose').focus();
  }

  function close() {
    lightbox.hidden = true;
    lbImg.removeAttribute('src');
    document.body.style.overflow = '';
    if (lastFocus) lastFocus.focus();
  }

  grid.addEventListener('click', e => {
    const item = e.target.closest('.gallery__item');
    if (!item) return;
    e.preventDefault();
    open(Number(item.dataset.index));
  });

  document.getElementById('lightboxClose').addEventListener('click', close);
  document.getElementById('lightboxPrev').addEventListener('click', () => show(current - 1));
  document.getElementById('lightboxNext').addEventListener('click', () => show(current + 1));
  lightbox.addEventListener('click', e => {
    if (e.target === lightbox || e.target.classList.contains('lightbox__figure')) close();
  });

  document.addEventListener('keydown', e => {
    if (lightbox.hidden) return;
    if (e.key === 'Escape') close();
    else if (e.key === 'ArrowLeft') show(current - 1);
    else if (e.key === 'ArrowRight') show(current + 1);
  });

  // Swipe on touch devices
  let touchX = null;
  lightbox.addEventListener('touchstart', e => { touchX = e.touches[0].clientX; }, { passive: true });
  lightbox.addEventListener('touchend', e => {
    if (touchX === null) return;
    const dx = e.changedTouches[0].clientX - touchX;
    if (Math.abs(dx) > 50) show(current + (dx < 0 ? 1 : -1));
    touchX = null;
  });

  // Start on the year in the URL (e.g. gallery.html#2023), otherwise the newest
  selectYear(location.hash.slice(1), false);
  window.addEventListener('hashchange', () => selectYear(location.hash.slice(1), false));
})();
